<a href="https://colab.research.google.com/github/akshay2904/1999/blob/master/Working.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import os
import glob

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path = r"/content/drive/My Drive/Case Comp/Training_final"

# Use glob to get all the CSV files in the folder
csv_files = glob.glob(os.path.join(path, "*.csv"))

# Loop over the list of CSV files
for f in csv_files:
    # Read the CSV file
    df = pd.read_csv(f)

    # Print the location and filename
    print('Location:', f)
    print('File Name:', f.split("/")[-1])  # Use forward slash for paths in Google Colab/Unix

    # Print the content
    display(df)

Location: /content/drive/My Drive/Case Comp/Training_final/humana_mays_target_members.csv
File Name: humana_mays_target_members.csv

,calendar_year,product_type,plan_category,preventive_visit_gap_ind,id
0,2023,LPPO,Medicare Advantage,0,380667
1,2023,LPPO,Medicare Advantage,0,378860
2,2023,LPPO,Medicare Advantage,1,1370287
3,2023,LPPO,Medicare Advantage,0,184540
4,2023,LPPO,Medicare Advantage,0,1628837
...,...,...,...,...,...
1527899,2023,LPPO,Medicare Advantage,1,1065218
1527900,2023,LPPO,Medicare Advantage,1,1597708
1527901,2023,LPPO,Medicare Advantage,1,328428
1527902,2023,LPPO,Medicare Advantage,1,286064
1527903,2023,LPPO,Medicare Advantage,0,1812983

Location: /content/drive/My Drive/Case Comp/Training_final/Additional Features.csv
File Name: Additional Features.csv

,cms_frailty_ind,cms_tot_ma_payment_amt,cms_tot_partd_payment_amt,atlas_recfacpth14,atlas_ffrpth14,atlas_fsrpth14,atlas_grocpth14,atlas_povertyallagespct,cci_score,fci_score,dcsi_score,id
0,1.0,NaN,NaN,0.048228,0.569086,0.356884,0.183265,17.5,7.0,5.0,4.0,1352611
1,0.0,1103.23,178.83,0.039119,0.508548,0.782381,0.117357,12.1,4.0,5.0,4.0,299881
2,0.0,398.96,150.99,0.118075,0.688773,0.551018,0.098396,15.9,3.0,1.0,0.0,1191826
3,0.0,967.76,161.81,0.040908,0.368173,0.204541,0.286357,22.9,4.0,4.0,0.0,1772108
4,0.0,849.85,44.03,0.000000,0.682271,0.367377,0.472342,30.4,4.0,3.0,4.0,171691
...,...,...,...,...,...,...,...,...,...,...,...,...
1527899,1.0,NaN,NaN,0.046311,0.555736,0.625203,0.138934,20.7,2.0,3.0,1.0,376551
1527900,1.0,NaN,NaN,0.042100,0.841999,1.052499,0.378900,14.1,2.0,0.0,0.0,1637412
1527901,1.0,NaN,NaN,0.072404,0.699908,0.724043,0.096539,11.6,2.0,0.0,0.0,338186
1527902,1.0,NaN,NaN,0.062459,0.780738,0.624590,0.197787,15.8,2.0,0.0,0.0,351507
1527903,1.0,NaN,NaN,0.080820,0.794147,0.748466,0.179210,20.1,3.0,0.0,0.0,375553

Location: /content/drive/My Drive/Case Comp/Training_final/Control Point.csv
File Name: Control Point.csv

,cnt_cp_emails_0,cnt_cp_emails_1,cnt_cp_emails_2,cnt_cp_emails_3,cnt_cp_emails_4,cnt_cp_emails_5,cnt_cp_emails_6,cnt_cp_emails_7,cnt_cp_emails_8,cnt_cp_emails_9,...,cnt_cp_livecall_8,cnt_cp_livecall_9,cnt_cp_livecall_10,cnt_cp_livecall_11,cnt_cp_emails_pmpm_ct,cnt_cp_print_pmpm_ct,cnt_cp_vat_pmpm_ct,cnt_cp_webstatement_pmpm_ct,cnt_cp_livecall_pmpm_ct,id
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.000000,0.000000,11.500000,0.0,1352611
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.500000,1.000000,2.416667,0.0,299881
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.166667,1.000000,2.166667,0.0,1191826
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.083333,2.166667,1.583333,0.0,1772108
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.083333,0.250000,4.250000,0.0,171691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527899,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,3.000000,0.000000,10.000000,0.0,376551
1527900,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,1.000000,0.000000,2.000000,0.0,1637412
1527901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,2.000000,0.0,338186
1527902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,1.000000,0.0,351507
1527903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,1.000000,0.0,375553

Location: /content/drive/My Drive/Case Comp/Training_final/Cost & Utilization.csv
File Name: Cost & Utilization.csv

,nonpar_clm_ct_pmpm,nonpar_allowed_pmpm_cost,nonpar_net_paid_pmpm_cost,nonpar_cob_paid_pmpm_cost,nonpar_coins_pmpm_cost,nonpar_copay_pmpm_cost,nonpar_deduct_pmpm_cost,nonpar_mbr_resp_pmpm_cost,nonpar_ds_clm,oontwk_clm_ct_pmpm,...,bh_rtc_admit_ct_pmpm,bh_rtc_admit_days_pmpm,bh_psyc_visit_ct_pmpm,total_ip_acute_admit_days_pmpm,total_ip_ltach_admit_days_pmpm,total_ip_maternity_admit_days_pmpm,total_ip_mhsa_admit_days_pmpm,total_ip_rehab_admit_days_pmpm,total_ip_snf_admit_days_pmpm,id
0,1.000000,201.670000,197.635000,0.0,0.0,0.0,0.0,0.0,40.0,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1352611
1,0.166667,9.913333,9.913333,0.0,0.0,0.0,0.0,0.0,101.0,0.166667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,299881
2,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,480.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1191826
3,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,480.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1772108
4,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,480.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,171691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527899,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,480.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,376551
1527900,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,480.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1637412
1527901,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,480.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,338186
1527902,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,480.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,351507
1527903,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,480.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,375553

Location: /content/drive/My Drive/Case Comp/Training_final/Demographics.csv
File Name: Demographics.csv

,lang_spoken_cd,rucc_category,riskarr_downside,riskarr_upside,riskarr_rewards,riskarr_global,id
0,ENG,1-Metro,0.0,1.0,0.0,0.0,1352611
1,ENG,2-Metro,0.0,0.0,0.0,0.0,299881
2,NaN,2-Metro,0.0,0.0,0.0,0.0,1191826
3,ENG,7-Nonmetro,0.0,1.0,0.0,0.0,1772108
4,NaN,7-Nonmetro,0.0,0.0,0.0,0.0,171691
...,...,...,...,...,...,...,...
1527899,ENG,6-Nonmetro,0.0,1.0,0.0,0.0,376551
1527900,ENG,8-Nonmetro,0.0,0.0,0.0,0.0,1637412
1527901,NaN,2-Metro,0.0,0.0,0.0,0.0,338186
1527902,ENG,3-Metro,0.0,0.0,0.0,0.0,351507
1527903,ENG,2-Metro,0.0,0.0,0.0,0.0,375553

Location: /content/drive/My Drive/Case Comp/Training_final/Pharmacy Utilization.csv
File Name: Pharmacy Utilization.csv

,rx_overall_pmpm_cost,rx_overall_net_paid_pmpm_cost,rx_overall_coins_pmpm_cost,rx_overall_copay_pmpm_cost,rx_overall_deduct_pmpm_cost,rx_overall_mbr_resp_pmpm_cost,rx_overall_gpi_pmpm_ct,rx_overall_dist_gpi6_pmpm_ct,rx_overall_pmpm_ct,rx_tier_1_pmpm_ct,rx_tier_2_pmpm_ct,rx_tier_3_pmpm_ct,rx_tier_4_pmpm_ct,rx_days_since_last_script,rx_pharmacies_pmpm_ct,rx_perphy_pmpm_ct,id
0,1369.120000,1366.335000,2.785000,0.000000,0.00,2.785000,11.500000,8.500000,15.000000,4.000000,3.500000,3.500000,0.500000,7.0,1.000000,0.0,1352611
1,44.848330,16.679167,0.000000,28.169167,0.00,28.169167,3.166667,1.166667,3.166667,1.583333,1.166667,0.250000,0.166667,11.0,0.166667,0.0,299881
2,2.383333,0.716667,0.000000,1.666667,0.00,1.666667,2.250000,0.500000,2.250000,1.916667,0.333333,0.000000,0.000000,12.0,0.166667,0.0,1191826
3,707.318360,675.651700,0.000000,23.750000,0.00,31.666666,1.166667,0.500000,1.166667,0.666667,0.166667,0.333333,0.000000,26.0,0.083333,0.0,1772108
4,44.096670,15.378333,0.066667,3.063333,40.00,28.718334,3.083333,1.250000,3.083333,3.083333,0.000000,0.000000,0.000000,50.0,0.083333,0.0,171691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527899,16.480000,15.130000,0.000000,1.350000,0.00,1.350000,2.000000,2.000000,2.000000,1.000000,1.000000,0.000000,0.000000,2.0,1.000000,0.0,376551
1527900,2.750000,0.000000,0.000000,0.000000,2.75,2.750000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,27.0,1.000000,0.0,1637412
1527901,53.760000,5.160000,0.000000,0.000000,53.76,48.600000,6.000000,5.000000,6.000000,6.000000,0.000000,0.000000,0.000000,2.0,1.000000,0.0,338186
1527902,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,480.0,0.000000,0.0,351507
1527903,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,480.0,0.000000,0.0,375553

Location: /content/drive/My Drive/Case Comp/Training_final/Sales Channel.csv
File Name: Sales Channel.csv

                     channel       id
0                      Field  1069625
1                      Field   326883
2            Consumer Direct  1559370
3            Consumer Direct    13259
4                      Field  1254048
...                      ...      ...
1527899                Field   925272
1527900  Partner Call Center  1523752
1527901  Partner Call Center   503154
1527902  Partner Call Center   485798
1527903      Consumer Direct    81288

[1527904 rows x 2 columns]

Location: /content/drive/My Drive/Case Comp/Training_final/Social Determinants of Health.csv
File Name: Social Determinants of Health.csv

,rwjf_premature_death_rate,rwjf_poor_health_pct,rwjf_uninsured_adults_pct,rwjf_pcp_rate,rwjf_preventable_ip_rate,rwjf_adult_smoking_pct,rwjf_adult_obesity_pct,rwjf_teen_births_rate,rwjf_homicides_rate,rwjf_high_school_pct,...,rwjf_disconnect_youth_pct,rwjf_home_ownership_pct,rwjf_housing_cost_burden_pct,rwjf_flu_vax,rwjf_suicides_rate,rwjf_broadband_access,rwjf_diabetes_monitor_pct,rwjf_healthcare_cost,rwjf_drug_deaths_modl_rate,id
0,8671.084,0.216076,0.197464,0.000265,52.68,0.195525,0.398,24.084312,10.428421,0.870000,...,0.075730,0.676266,0.159998,0.49,14.443182,0.855341,0.863121,9750.99,6.0,1352611
1,7439.620,0.193420,0.072883,0.000603,32.74,0.196184,0.311,14.443236,NaN,0.970000,...,NaN,0.707001,0.109818,0.55,24.068380,0.833414,0.881720,8749.57,11.0,299881
2,8363.172,0.211875,0.090306,0.000797,33.49,0.218531,0.348,22.917480,3.817668,0.940000,...,0.078956,0.645821,0.120681,0.56,14.110594,0.840763,0.896078,9544.74,12.0,1191826
3,10805.334,0.281196,0.092180,0.000284,55.07,0.281043,0.330,45.366043,6.421520,0.930000,...,NaN,0.783335,0.081525,0.37,16.813110,0.685470,0.890449,10177.70,12.0,1772108
4,14181.182,0.313580,0.088424,0.000586,107.71,0.289167,0.407,57.787067,6.553408,0.970000,...,0.157454,0.699067,0.147324,0.34,19.058668,0.719067,0.821641,13539.30,15.0,171691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527899,6027.820,0.198544,0.094016,0.000574,38.86,0.241388,0.375,13.393764,NaN,0.765619,...,0.063163,0.733426,0.139688,0.37,14.887681,0.770939,0.844130,8706.94,5.0,376551
1527900,9694.119,0.180898,0.217170,0.000462,38.55,0.202963,0.287,31.518625,NaN,0.940000,...,NaN,0.790354,0.093154,0.48,21.691614,0.832148,0.858362,9921.92,15.0,1637412
1527901,7256.559,0.177475,0.155202,0.000421,41.52,0.205468,0.376,20.225464,NaN,0.870000,...,NaN,0.797562,0.091311,0.58,17.806608,0.835111,0.921171,9944.39,9.0,338186
1527902,9736.558,0.219709,0.204958,0.001307,71.80,0.211616,0.343,28.938050,5.891138,0.923548,...,0.093761,0.610443,0.123964,0.50,18.880125,0.777853,0.871505,10394.01,10.0,351507
1527903,7337.949,0.164136,0.074417,0.001042,41.27,0.186013,0.313,13.778982,4.860438,0.760366,...,0.033583,0.584713,0.158210,0.44,14.154781,0.823281,0.874962,10073.19,8.0,375553

Location: /content/drive/My Drive/Case Comp/Training_final/Web Activity.csv
File Name: Web Activity.csv

,days_since_last_login,login_pmpm_ct,login_count_0,login_count_1,login_count_2,login_count_3,login_count_4,login_count_5,login_count_6,login_count_7,login_count_8,login_count_9,login_count_10,login_count_11,id
0,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1352611
1,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,299881
2,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1191826
3,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1772108
4,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,171691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527899,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,376551
1527900,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1637412
1527901,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,338186
1527902,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,351507
1527903,480.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,375553

Location: /content/drive/My Drive/Case Comp/Training_final/MEMBER_DATA.csv
File Name: MEMBER_DATA.csv

,consec_tenure_month,all_mm_tenure,tenure_band,dual_eligible_ind,disabled_ind,lis_ind,id
0,6,6,0 - 0.5 YEARS,N,N,N,1551235
1,59,59,4 - 5 YEARS,N,Y,N,1643841
2,119,119,7+ YEARS,N,N,N,540296
3,24,24,1.5 - 2 YEARS,N,Y,N,729600
4,60,76,4 - 5 YEARS,N,N,N,716836
...,...,...,...,...,...,...,...
1527899,4,4,0 - 0.5 YEARS,N,N,N,1551651
1527900,23,23,1.5 - 2 YEARS,N,N,N,1584607
1527901,3,3,0 - 0.5 YEARS,N,N,N,1246390
1527902,24,24,1.5 - 2 YEARS,N,Y,N,695942
1527903,12,12,0.5 - 1 YEARS,N,N,N,209485

<ipython-input-6-e3ae02dbc4b4>:9: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

Location: /content/drive/My Drive/Case Comp/Training_final/QUALITY_DATA.csv
File Name: QUALITY_DATA.csv

,measurement_year,measure_name,measure_desc,measure_type,base_event_date,compliant_cnt,eligible_cnt,id
0,2020,ADH (DIAB),Medication Adherence for Diabetes Medications,Patient Safety,NaN,1.0,1,40240
1,2020,ADH (ACE),Medication Adherence for Hypertension (RAS ant...,Patient Safety,NaN,1.0,1,40240
2,2020,ABA,Adult BMI Assessment,HEDIS,NaN,0.0,1,193657
3,2020,ADH (ACE),Medication Adherence for Hypertension (RAS ant...,Patient Safety,NaN,0.0,1,1685072
4,2020,ADH (STATIN),Medication Adherence for Cholesterol (Statins),Patient Safety,NaN,1.0,1,1685072
...,...,...,...,...,...,...,...,...
33572236,2021,TEX,Dr Talks Mental Health,Patient Experience,19FEB2021,1.0,1,233257
33572237,2020,TEX,Dr Talks Mental Health,Patient Experience,10JAN2020,0.0,1,732194
33572238,2020,TEX,Dr Talks Mental Health,Patient Experience,22JAN2020,1.0,1,401639
33572239,2020,TEX,Dr Talks Mental Health,Patient Experience,12FEB2020,1.0,1,401639
33572240,2021,TEX,Dr Talks Mental Health,Patient Experience,18JUN2021,1.0,1,401639

Location: /content/drive/My Drive/Case Comp/Training_final/humana_mays_target_member_details.csv
File Name: humana_mays_target_member_details.csv

,generic_grouper,unattributed_provider,sex_cd,age,veteran_ind,mco_contract_nbr,plan_benefit_package_id,pbp_segment_id,state_of_residence,county_of_residence,region,race,id
0,Y,N,F,74,N,H5216,72,0,FL,POLK,Florida,NaN,1081255
1,N,N,M,83,N,H5216,334,0,MS,HINDS,Gulf South,BLACK,9020
2,Y,Y,F,68,N,H5216,43,1,TX,GRAYSON,South Central,N AMERICAN NATIVE,1089029
3,N,N,F,66,N,H5216,805,0,AL,HOUSTON,Gulf South,WHITE,872819
4,Y,N,M,74,N,H5216,805,0,TN,SUMNER,Gulf South,WHITE,830574
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527899,Y,N,M,74,Y,H5216,278,1,MN,ANOKA,Central,NaN,1153850
1527900,N,N,M,78,Y,H5216,255,0,MT,JEFFERSON,Intermountain,WHITE,11169
1527901,N,N,F,72,N,H7617,801,0,SC,CHARLESTON,Southeast,NaN,521682
1527902,N,N,M,80,N,H5216,285,0,OH,MORROW,Midwest,NaN,1556452
1527903,N,N,F,70,N,H5216,805,0,TX,BEXAR,South Central,BLACK,488579

<ipython-input-6-e3ae02dbc4b4>:9: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

Location: /content/drive/My Drive/Case Comp/Training_final/humana_mays_target_member_visit_claims.csv
File Name: humana_mays_target_member_visit_claims.csv

,dos_year,clm_unique_key,serv_date_skey,pcp_visit,annual_wellness,humana_paf,preventative_visit,comp_physical_exam,ihwa,fqhc_visit,...,physical_therapist_visit,cardiologist_visit,gastroenterologist_visit,orthopedist_visit,obgyn_visit,nephroloogist_visit,pulmonologist_visit,urgent_care_visit,er_visit,id
0,2021,90000007336,20210105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,733133
1,2021,90000030533,20210107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1296887
2,2021,90000039180,20210111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1331806
3,2021,90000048032,20210112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1548280
4,2021,90000070091,20210118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,689644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19456791,2021,999927000478501203,20210223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1348185
19456792,2022,999961000483212503,20220608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,659891
19456793,2022,999962000484641903,20221031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,724256
19456794,2021,999974100479592803,20210428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,1314346
19456795,2021,999979000478441503,20210219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,971401

Location: /content/drive/My Drive/Case Comp/Training_final/humana_mays_target_member_conditions.csv
File Name: humana_mays_target_member_conditions.csv

,cond_key,chronicity,cond_desc,hcc_model_type,cms_model_vers_cd,membership_year,id
0,226,Chronic,"Heart Failure, Except End-Stage and Acute",MEDICAL,V28,2023,993642
1,94,Chronic,Systemic Lupus Erythematosus and Other Specifi...,MEDICAL,V28,2023,993642
2,329,Chronic,"Chronic Kidney Disease, Moderate Stage 3, Exce...",MEDICAL,V28,2023,993642
3,81,Chronic,Ulcerative Colitis,MEDICAL,V28,2023,803124
4,47,Chronic,Disorders of Immunity,MEDICAL,V24,2023,803124
...,...,...,...,...,...,...,...
4009337,37,Chronic,Diabetes with Chronic Complications,MEDICAL,V28,2023,654526
4009338,238,Chronic,Specified Heart Arrhythmias,MEDICAL,V28,2023,654526
4009339,329,Chronic,"Chronic Kidney Disease, Moderate Stage 3, Exce...",MEDICAL,V28,2023,654526
4009340,38,Chronic,"Diabetes with Glycemic, Unspecified, or No Com...",MEDICAL,V28,2023,1124053
4009341,280,Chronic,"Chronic Obstructive Pulmonary Disease, Interst...",MEDICAL,V28,2023,1891210

In [ ]:
folder_path = r'/content/drive/My Drive/Case Comp/Training_final'

# Read the CSV files using forward slashes for file paths
additional_features = pd.read_csv(f'{folder_path}/Additional Features.csv')
control_point = pd.read_csv(f'{folder_path}/Control Point.csv')
cost_utilization = pd.read_csv(f'{folder_path}/Cost & Utilization.csv')
demographics = pd.read_csv(f'{folder_path}/Demographics.csv')
pharmacy_utilization = pd.read_csv(f'{folder_path}/Pharmacy Utilization.csv')
sales_channel = pd.read_csv(f'{folder_path}/Sales Channel.csv')
social_determinants = pd.read_csv(f'{folder_path}/Social Determinants of Health.csv')
web_activity = pd.read_csv(f'{folder_path}/Web Activity.csv')
member_data = pd.read_csv(f'{folder_path}/MEMBER_DATA.csv')
quality_data = pd.read_csv(f'{folder_path}/QUALITY_DATA.csv')
member_details = pd.read_csv(f'{folder_path}/humana_mays_target_member_details.csv')
member_claim = pd.read_csv(f'{folder_path}/humana_mays_target_member_visit_claims.csv')
member_condition = pd.read_csv(f'{folder_path}/humana_mays_target_member_conditions.csv')
target_members = pd.read_csv(f'{folder_path}/humana_mays_target_members.csv')

<ipython-input-7-2e70fda8bd75>:13: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  quality_data = pd.read_csv(f'{folder_path}/QUALITY_DATA.csv')
<ipython-input-7-2e70fda8bd75>:15: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  member_claim = pd.read_csv(f'{folder_path}/humana_mays_target_member_visit_claims.csv')

In [ ]:
merged_df = target_members.merge(additional_features, on='id', how='left')
merged_df = merged_df.merge(control_point, on='id', how='left')
merged_df = merged_df.merge(cost_utilization, on='id', how='left')
merged_df = merged_df.merge(demographics, on='id', how='left')
merged_df = merged_df.merge(pharmacy_utilization, on='id', how='left')
merged_df = merged_df.merge(sales_channel, on='id', how='left')
merged_df = merged_df.merge(social_determinants, on='id', how='left')
merged_df = merged_df.merge(web_activity, on='id', how='left')
merged_df = merged_df.merge(member_data, on='id', how='left')
merged_df = merged_df.merge(member_claim, on='id', how='left')
merged_df= merged_df.merge(member_condition, on='id', how='left')

In [ ]:
merged_df.columns
merged_df.describe()

In [ ]:
# Check for columns with missing values
null_counts = merged_df.isnull().sum()

# Get the list of columns with missing values
columns_with_missing = null_counts[null_counts > 0]

# Print the list of columns and the count of missing values in each
print(columns_with_missing)

In [ ]:

# 1. Handle Missing Values
# Get a list of columns with missing values
missing_columns = merged_df.columns[merged_df.isnull().sum() > 0]
print("Columns with missing values:", missing_columns)

In [ ]:
duplicates = merged_df[merged_df.duplicated(subset='id', keep=False)]

# Display the duplicate rows

print(duplicates)

In [ ]:
numeric_columns = merged_df.select_dtypes(include=[np.number]).columns
categorical_columns = merged_df.select_dtypes(include=['object']).columns

In [ ]:
from sklearn.impute import SimpleImputer

numeric_imputer = SimpleImputer(strategy='median')
categorical_imputer = SimpleImputer(strategy='constant', fill_value='Unknown')

In [ ]:
merged_df.shape

In [ ]:
non_numeric_columns = merged_df.select_dtypes(include=['object']).columns
print("Non-Numeric Columns:", non_numeric_columns)

In [ ]:
# Use One-Hot Encoding for all categorical columns
merged_df_encoded = pd.get_dummies(merged_df, drop_first=True)

# Check the new DataFrame
print(merged_df_encoded.head())

In [ ]:
merged_df.to_csv('/content/drive/My Drive/Case Comp/final_df.csv')

NameError: name 'merged_df' is not defined

NameError: name 'merged_df' is not defined